// Auto-generated by scripts/generate-versions.ts — do not edit manually.
// Re-generated on every prepack from packages/core and packages/config package.json.
export const CORE_VERSION = '^0.3.0';
export const CONFIG_VERSION = '^0.1.0';
